name: sample
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter_bloc:
  equatable:
  build_grpc_channel:
  proto_sample:
    git: git@github.com:APoliaskovska/proto_sample.git
  flutter:
    sdk: flutter
  easy_localization: ^3.0.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  animated_splash_screen: ^1.3.0
  http: ^0.13.5
  flutter_secure_storage: ^5.0.2
  firebase_core: ^1.20.1
  firebase_crashlytics: ^2.8.7
  local_auth: ^2.1.2
  dots_indicator: ^2.1.0
  file_picker: ^5.0.1
  firebase_messaging: ^13.0.0
  flutter_share: ^2.0.0
  path_provider: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/onboarding/
    - assets/translations/

  fonts:
    - family: Roboto
    - fonts:
      - asset: assets/fonts/Roboto-Regular.ttf
        weight: 400
      - asset: assets/fonts/Roboto-Medium.ttf
        weight: 500
      - asset: assets/fonts/Roboto-Bold.ttf
        weight: 700
      - asset: assets/fonts/Roboto-Black.ttf
        weight: 900

    #
    # For details regarding fonts from package dependencies,
    # see https://flutter.dev/custom-fonts/#from-packages